## Variables
@popupId = 27

### 팝업 등록
POST http://localhost:8081/api/v1/popups
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="name";

name

--boundary
Content-Disposition: form-data; name="description";

description

--boundary
Content-Disposition: form-data; name="address";

address

--boundary
Content-Disposition: form-data; name="managerName";

managerName

--boundary
Content-Disposition: form-data; name="phoneNumber";

01012345678

--boundary
Content-Disposition: form-data; name="startDate";

2024-06-19T10:00:00

--boundary
Content-Disposition: form-data; name="endDate";

2024-07-19T10:00:00

--boundary
Content-Disposition: form-data; name="thumbnail"; filename="thumbnail.jpeg";
Content-Type: image/png

< images/image.png

--boundary
Content-Disposition: form-data; name="images"; filename="image1.png";
Content-Type: image/png

< images/image.png

### 호스트의 상태별 팝업 목록 조회
### 승인 상태 : approvalStatusBy=(reviewing, approved, rejected)
### 팝업 상태 : popupStatus=(scheduled, in_progress, completed, canceled)
GET http://localhost:8081/api/v1/popups?approvalStatusBy=reviewing&popupStatus=scheduled

### 팝업 상세 조회
GET http://localhost:8081/api/v1/popups/{{popupId}}

### 팝업 수정
PUT http://localhost:8081/api/v1/popups/{{popupId}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="name";

update name

--boundary
Content-Disposition: form-data; name="description";

update description

--boundary
Content-Disposition: form-data; name="address";

update address

--boundary
Content-Disposition: form-data; name="managerName";

update managerName

--boundary
Content-Disposition: form-data; name="phoneNumber";

01099999999

--boundary
Content-Disposition: form-data; name="startDate";

2024-07-19T10:00:00

--boundary
Content-Disposition: form-data; name="endDate";

2024-08-19T10:00:00

--boundary
Content-Disposition: form-data; name="thumbnail"; filename="thumbnail.jpeg";
Content-Type: image/png

< images/image.png

--boundary
Content-Disposition: form-data; name="images"; filename="image1.png";
Content-Type: image/png

< images/image.png

### 팝업 취소
PATCH http://localhost:8081/api/v1/popups/{{popupId}}